### ISSUE TITLE
jars bundled into gems should not be unzipped

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-jar-plugin#19]
Some [gems](https://github.com/slyphon/log4j_gem) include jar files within their codebases which they require to function correctly.

Setting aside whether or not I think this is a "good idea" or not, the jar plugin should not futz with the contents of gems that are being included in the shadow jar.

See johnrengelman/shadow#111 for the upstream question about how to accomplish this

**Comment by mkristian** [comment]
will not be unzipped any more
