### ISSUE TITLE
Issue with rake running with incorrect path

### ISSUE THREAD

**Issue by blaines** [jruby-gradle/jruby-gradle-jar-plugin#23]
Expected `java -jar build/libs/example.jar -T` to output a list of rake tasks inside the .jar, instead rake appears to be running from and searching for tasks in the current directory.

Rakefile
```
puts File.expand_path(File.dirname(__FILE__) + '/tasks')
# Load all our tasks from the tasks directory
Dir[File.expand_path(File.dirname(__FILE__) + '/tasks/*.rake')].each do |f|
  load f
end
```
In my codebase, `.rake` files are located inside `lib`
```
   lib/tasks/
   lib/tasks/example_task.rake
   Rakefile
```

In the .jar the tasks directory is in the root...
```
   29 tasks/
   30 tasks/example_task.rake
   31 Rakefile
```

When I run `java -jar build/libs/example.jar -T` any tasks I have locally (outside the .jar) are output instead of tasks bundled into the .jar

**Comment by mkristian** [comment]
rake now works with unexploded jar and an included Rakefile. rake still fails with rspec (and possible similar cases) - see: https://github.com/jruby/jruby/issues/2969 and https://github.com/jruby/jruby/issues/2968

otherwise it works now - closing
