### ISSUE TITLE
embedded gems need directory file .jrubydir

### ISSUE THREAD

**Issue by mkristian** [jruby-gradle/jruby-gradle-jar-plugin#29]
when embedding gems in jar they need the directory info for each directory (mydir) in a file  mydir/.jrubydir which is just the directory listing, each entry in one line. see https://github.com/jruby/jruby/blob/master/core/src/main/ruby/jruby/commands.rb#L16 and https://github.com/jruby/warbler/issues/299

only then those gems can be used by fancy j2ee containers or osgi framework.

**Comment by rtyler** [comment]
I'm a bit confused, does every single gem directory need a `.jrubydir`?

**Comment by mkristian** [comment]
as well the directory where you store ruby files.

the reason is that the moment you do not have classloader which does use jars, jruby has no way to find the directory listings. most gems do work without this but the moment you the code does something like 
```
Dir[ 'initializers/*rb' ].each { |f| require f }
```
you need those .jrubydir if you want the file to be usable with "classloader" in general. jruby-9k is almost away from finding and exploring jars (which only works with URLClassloaders). jruby-rack will allow such a setup in future (https://github.com/jruby/jruby-rack/pull/191). and it is the only way to get those gems work on OSGi.

jruby-1.7.19 will allow to ```Dir.chdir( "uri:classloader://" )``` which is only possible when there is such .jrubydir file in the root of the classloader (only then it is recognized as directory). with this it is possible to create a runnable which does not need to "unpack itself", just run off the jar file itself.

see also: http://blog.mkristian.tk/2014/12/improvements-of-jruby-java-integration.html

**Comment by rtyler** [comment]
@mkristian I'm not sure I understand the problem here? I'm assuming that this has something to do with using a `.jar` file as a library instead of a stand-alone executable?

In which case @ysb33r would be very interested :)


I'll discuss this further on internal IM with you, but this might be something worth fixing on @Lookout's dime

**Comment by mkristian** [comment]
yes, it is the library case where this is important.

**Comment by ysb33r** [comment]
> when embedding gems in jar they need the directory info for each directory (mydir) in a file mydir/.jrubydir which is just the directory listing, each entry in one line

Is this for every file in the subtree or only the toplevel directories? For instance if the unpacked GEM is

```
gems/credit_card_validator-1.1.0
gems/credit_card_validator-1.1.0/bin
gems/credit_card_validator-1.1.0/bin/credit_card_validator
gems/credit_card_validator-1.1.0/History.txt
gems/credit_card_validator-1.1.0/lib
gems/credit_card_validator-1.1.0/lib/credit_card_validator
gems/credit_card_validator-1.1.0/lib/credit_card_validator/validator.rb
gems/credit_card_validator-1.1.0/lib/credit_card_validator.rb
gems/credit_card_validator-1.1.0/Manifest.txt
gems/credit_card_validator-1.1.0/Rakefile
gems/credit_card_validator-1.1.0/README.rdoc
gems/credit_card_validator-1.1.0/test
gems/credit_card_validator-1.1.0/test/test_credit_card_validator.rb
gems/credit_card_validator-1.1.0/test/test_helper.rb
```
[1] Is there supposed to be a `gems/.jrubydir` file containing only `credit_card_validator-1.1.0` ?

[2] What is the content `gems/credit_card_validator-1.1.0/.jrubydir` suposed to be?

Is it 
```
bin
History.txt
lib
Manifest.txt
Rakefile
README.rdoc
test
```

or all descendent files with relative paths below `credit_card_validator-1.1.0`?

**Comment by mkristian** [comment]
actually for rubygems itself the specifications directory is the most important, since something like ```Dir[ GEM_PATH + "/specifications/*gemspec"]``` happens to find the installed gems !

just recently I needed to add the root directory as well to allow ```GEM_PATH=uri:classloader://``` to work.

you need it for ALL directories - in the end you never know when such directory globs happens and where. each directory should have ".jrubydir" which is essentially: ```cd mydir; ls -1a > .jrubydir```

whether the "." and ".." is really needed I can not say, but I included them in https://github.com/jruby/jruby/blob/master/core/src/main/ruby/jruby/commands.rb#L16
to be more in line what happens on the regular filesystem.

**Comment by ysb33r** [comment]
One solution is to potentially patch the jrubyPrepareGems task so that it adds the `.jrubydir` files  as it unpacks the GEMs during the Grafle build.

**Comment by mkristian** [comment]
yes, the jruby-gradle-war-plugin would need the same when you want the war
to work on "exotic" servlet containers (or as web-archive-osgi-bundle).

On Thu, Jan 15, 2015 at 10:09 PM, Schalk W. Cronjé <notifications@github.com

**Comment by mkristian** [comment]
done
