### ISSUE TITLE
reproducible builds with gem dependencies

### ISSUE THREAD

**Issue by mkristian** [jruby-gradle/jruby-gradle-jar-plugin#30]
the nature of using version ranges in dependencies is that the transitive dependency hull of the project can/will change over time. this means it is NOT possible or very difficult to reproduce a build from the past. for a library this is probably less a problem since there you want to keep the version ranges open (and/or hope semantic versioning works). for other projects like a rails-app or a sinatra-app I want to be able to rerun the build which went into production anytime in future.

in ruby world there is bundler which helps to address the problem by locking down the version of ALL dependencies.

to use gradle + bundler side by side is probably the way to go:

* bundler will manage the gem dependencies
* gradle will manage your build artifact or assembly

**Comment by rtyler** [comment]
I believe that [this dependency lock plugin](https://github.com/nebula-plugins/gradle-dependency-lock-plugin) addresses the behavior you're describing.

The problem with using a tool like bundler outside of the context of Gradle is that it would result in Gradle not being aware of the dependency tree in a meaning full way to avoid re-resolving dependencies, or associating dependencies with different configurations. It also causes many of bundlers weaknesses to affect the Gradle-based project (e.g. weak separation of groups, all gems must be present at install time, etc)

**Comment by mkristian** [comment]
right - I never did included such a feature with jruby-maven-plugins but via ruby-maven it works really nice to use Gemfile as DSL for maven. people found "pure" gem dependencies unusable when you have lots of gems because the dependency resoultion needs (literally) hundreds of pom.xml to do its jobs. there were reports that maven did an hour downloading on an empty local repository on such projects.

but again - some improvements here you pay with some disadvantages somewhere else. in the end one needs to pick which feels best suited ;)

**Comment by ysb33r** [comment]
> to use Gemfile as DSL for maven

I have been considering reading a Gemfile from Gradle in order to determine dependencies, but have not yet convinced myself whether it is a sensible thing to do. Currently Gradle + Torquebox does a good job of dependency resolution.
