### ISSUE TITLE
if there is not META-INF/init.rb just do not try to require it

### ISSUE THREAD

**Issue by mkristian** [jruby-gradle/jruby-gradle-jar-plugin#31]
the META-INF/init.rb is something which comes from jruby-rack and is meant as way to setup the ENV used by jruby-rack. warbler uses it as well in the same manner for runnable jars., i.e. when it detects a rack application it will include ```ENV['RACK_ENV']='production'```

whether the warbler defaults and magic makes sense I do not know, but if there is no such init.rb file, just do nothing and continue launching.

see also
https://github.com/mkristian/jruby-mains/blob/master/src/main/java/de/saumya/mojo/mains/JRubyMain.java#L65

**Comment by ysb33r** [comment]
Is this related to JARs or WARs? 

Currently the JAR implementation will look for a `init.rb` as a startup file if nothing if else is configured in the gradle script i.e.

```groovy
jrubyJavaBootstrap {
    jruby {
        initScript = 'bin/asciidoctor'
    }
}
```

**Comment by mkristian** [comment]
I coming from "warbler" (not really but I needed to work with it recently) there a runnable jar is something you can execute ```java -jar my.jar -S rake -T``` and even here the META-INF/init.rb is used to configure for example some environment variables like RACK_ENV or RAILS_ENV or BUNDLE_GEMFILE ....

but maybe I am on the wrong track but in my tests I have no need for a startup file but need the bin-stubs of the embedded gems to be found via ```-S``` switch.

**Comment by mkristian** [comment]
the ```initScript runnable()``` honors this,
