### ISSUE TITLE
classloader semantics

### ISSUE THREAD

**Issue by mkristian** [jruby-gradle/jruby-gradle-jar-plugin#33]
jruby has two classloaders:

* the classloader with jruby itself - main-classloader
* each runtime has its own classloader which has the main-classloader as parent - jruby-classloader

so jar-dependencies and jbundler uses ```require 'some.jar'``` which loads this jar into the jruby-classloader
this is a dynamic process and completely inside the realm of ruby code.

this allows the ruby code to decide which jars to load and which one not to load. this is something I used yesterday for a workaround: 

https://github.com/lookout/leafy/blob/master/leafy-metrics/leafy-metrics.gemspec
declares slf4j-simple which is never used during runtime:
https://github.com/lookout/leafy/blob/master/leafy-metrics/lib/leafy-metrics_jars.rb

currently it is used only when running tests.

now the gem-artifacts from the torquebox maven repository can have jar dependencies and jruby-gradle-jar-plugin readme basically says to use shadowJar to bundle them into a uberjar. this changes the classloader semantic drastically since all the jars are part of the main-classloader now and this one is static and outside the control of the ruby code.

with my example of leafy-metrics this means slf4j-simple is always part of the main-classloader and the ruby code can NOT decide to NOT use the jar.

so the proper way to bundle jar-dependencies would to build a local maven repository at the root of the jar: i.e. the org.slf4j:slf4j-api:1.7.7 artifact should be located org/slf4j/slf4-api/1.7.7/slf4j-api-1.7.7.jar and let jar-dependencies load it - let the ruby code decide whether when to load it ;)

**Comment by rtyler** [comment]
To avoid this behavior we're already using:

```ruby
ENV['JARS_NO_REQUIRE'] = 'true'
ENV['JBUNDLE_SKIP'] = 'true'
ENV['JARS_SKIP'] = 'true'
```

In many cases at @Lookout where we want to avoid this behavior from jbundler. I'm on the fence as to which approach is the right approach here. What you're proposing would put all the work on loading the included bytecode from a jar like slf4j into the `RubyRuntime`'s classloader wouldn't it? 

What happens if there are two `RubyRuntime` instances being created/executed inside the same JVM? (which is the case with Storm topologies)


I don't have strong opinion either way, I want to make sure jruby-gradle provides the best, most bug-free, experience on JRuby :)

**Comment by mkristian** [comment]
from the jruby point of view: each runtime has its own JRubyClassLoader. each ```require 'my.jar'``` will be loaded by its runtime into its JRubyClassLoader.

within one jvm one jruby=runtime can use 'slf4j-simple' and the other can use the 'slf4j-log4j' bridge and the third one can use 'logback' - they are all nicely separated per runtime. this is the jruby-classloader semantic.

this example does **not** work when you put all the jars + jruby into ONE classloader. 

and with leafy-metrics and its slf4j-simple it means it can create subtle bugs when using something like logback: it depends on the class-loading which slf4j binding is used (maybe there is warning that more then one bindings are present) or its depends on how the uberjar choose from duplicated classes.

another example is if there is an artifact which uses joda-time-1.6.x and things work standalone, but when bundled with jruby it might (again depends on which classes are picked when bundling the uberjar) blow up jruby since it depends on joda-time-2.x (joda-time 2 is mostly backward compatible to 1.6.x)

so want I propose is to bundle jar-dependencies like gems:

JARS_VENDOR=false JARS_HOME=. GEM_HOME=. GEM_PATH=. gem install rake rspec

take "gems" and "specification" directory and all the directories containing a jar and add them to the userjar.

not sure about jbundler but this does not seems to be relavent since build.gradle does not do anything with the Jarfile - as far I understand.

**Comment by mkristian** [comment]
```ENV['JBUNDLE_SKIP'] = 'true'``` is probably not needed unless you bundle jbundler gem as well

```ENV['JARS_SKIP'] = 'true'```` that is not using maven to install jar-dependencies

```ENV['JARS_NO_REQUIRE'] = 'true'``` is needed when the jars are in the same classloader as jruby itself

**Comment by mkristian** [comment]
added some intro for https://github.com/mkristian/jruby-mains which explains 'my vision'

**Comment by mkristian** [comment]
about the more then one runtime there is subtle issue when running via the regular org.jruby.Main entry-point where the second runtime just uses the jruby-classloader from the first runtime as parent and inherits all its resources: https://github.com/jruby/jruby/pull/2025

again it is easy to construct examples which just fail with such setup - the question is whether those example have practical implication.

IMO jruby just behave as much the same however you execute it.

**Comment by mkristian** [comment]
this is done now :)
