### ISSUE TITLE
TODO list for 0.1.4

### ISSUE THREAD

**Issue by ysb33r** [jruby-gradle/jruby-gradle-jar-plugin#40]
We need to do the following before releasing 0.1.4

1. Merge #38 
2. Remove support for and dependencies on shadowJar
3. Update the README with the new documentation - Explicitly state that it is a breaking change.
4. Mark the new jruby-mains as `@Incubating`
5. Update Spock framework to `1.0`
6. Remove `maven { url 'http://dl.bintray.com/rtyler/jruby' }`
7. Delay the use of JrubyVersion until last possible moment (see jruby-gradle/jruby-gradle-plugin#115)
8. FIx the hard-coded `0.2.0` in `JRubyJarPlugin` - https://github.com/jruby-gradle/jruby-gradle-jar-plugin/pull/38/files#diff-0db12cd653b5b3468ac21351b2bf8466R73

**Comment by mkristian** [comment]
on #38 I also 
* removed all references to shadowJar
* updated the README (a bit)
* removed the extra maven
