### ISSUE TITLE
Fat jar configuration should be maintained through the jrubyJar task

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-jar-plugin#41]
All configuration that has to deal with the creation of a self-contained executable JRuby jar artifact should be managed under the `jrubyJar` task, e.g.

```gradle
jrubyJar {
    initScript 'app.rb'
    defaultMain() /* optional, present unless otherwise specified */
    defaultGems() /* optional, present unless otherwise specified */
    configuration configurations.compile /* dependencies in this configuraiton are shaded in */
}
```

This task would take the ruby files added to the `main` sourceset and pull them into the jar

**Comment by mkristian** [comment]
the ```initScript``` is also optional. without the initScript you can pick any ruby script from the jar as file argument ```java -jar my.jar app.rb``` or any executable from the gems like ```java -jar my.jar -S rake```

**Comment by mkristian** [comment]
looks done with #47
