### ISSUE TITLE
Jar task should support creating Ruby-based library jars which include gems

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-jar-plugin#43]
Related to #42, in the use case of something like asciidoctorj, we would want to be able to include gems packed into the library jar, e.g.:

```gradle
jar {
  jruby {
    includeGems() /* takes optional gemInstallDir */
  }
}
```

**Comment by mkristian** [comment]
libraries can be done via 
```
jrubyJar {
   jruby {
      initScript library()
   }
}
```
or via
```
jar {
  jruby {
    defaultGems()
  }
}
```

if further functionality is needed I guess we start a new issue. closing
