### ISSUE TITLE
jrubyJar should throw StopTaskExecuteException if an initScript does not exist

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-jar-plugin#45]
This is with the current HEAD (`4b8de17`). I'm able to create a fat jar artifact that is executable, but I do not have `initScript 'foo.rb'` defined, nor have I created a `jar-bootstrap.rb`.

Currently the plugin happily creates the artfact, when it should really stop execution because this is an invalid artifact.

**Comment by mkristian** [comment]
initScript can be: 
* initScript 'app.rb' 
* initScript runnable() 

it also implies that defaultMains() is used.

**Comment by mkristian** [comment]
fixed with #47
