### ISSUE TITLE
Plugin should have a JRubyFatJar type which can be extended

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-jar-plugin#46]
Much of [this behavior](https://github.com/jruby-gradle/jruby-gradle-jar-plugin/commit/aea1f7a104274c1fcc79a6acbc29effbdd63c4b2#diff-0db12cd653b5b3468ac21351b2bf8466R76) I think should be consolidated into a `JRubyJar` task type which inherits from `Jar` and provides all the necessary "fat jar" functionality that we need.

I would like to be abler to extend this functionality, e.g.:

```gradle
task serviceJar(type: JRubyFatJar) {
    dependsOn myOtherCustomTasks
    archiveName 'foobar'
    from('special/dir')
}
```

To where the `.jrubydir` and other fat-jar magic are applied when my "foobar.jar" is created.

That'd be nice.

**Comment by mkristian** [comment]
fixed with #47
